trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Validate Template'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'MSDN Subcription'
    subscriptionId: '967d4b58-56c6-4522-80bb-36142c2a0217'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DEVAKSRG01'
    location: 'UK South'
    csmFile: '$(Pipeline.Workspace)/s/templates/aks/cluster.bicep'
    csmParametersFile: '$(Pipeline.Workspace)/s/templates/aks/cluster.bicepparam'
    deploymentMode: 'Validation'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Deploy Template'
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'MSDN Subcription'
    subscriptionId: '967d4b58-56c6-4522-80bb-36142c2a0217'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'DEVAKSRG01'
    location: 'UK South'
    csmFile: '$(Pipeline.Workspace)/s/templates/aks/cluster.bicep'
    csmParametersFile: '$(Pipeline.Workspace)/s/templates/aks/cluster.bicepparam'
    deploymentMode: 'Incremental'
